"""PDF ingestion and bounded prompt preparation.

The application reviews multiple PDFs as one project corpus, but every page
retains its source filename and 1-indexed page number for traceability.

Two different bounded views are produced:

* ``build_digest`` creates a small, fair-per-file opening-page digest used for
  the summary and repeated cross-reference context.
* ``chunk_pages`` creates detailed review chunks. It enforces both character
  and page-fragment limits, never mixes source files in one chunk, and splits
  an abnormally text-dense single page instead of allowing it to bypass the
  chunk budget.
"""

from dataclasses import dataclass

import fitz  # PyMuPDF

# Silences MuPDF's native repair/recovery warning stream. These warnings are
# still retrievable through get_and_clear_extraction_warnings() so genuine
# source-file problems remain diagnosable without flooding Streamlit logs.
fitz.TOOLS.mupdf_display_errors(False)
fitz.TOOLS.mupdf_display_warnings(False)


@dataclass
class Page:
    source_file: str
    page_num: int  # 1-indexed PDF page number
    text: str
    # A text-dense PDF page can be split into prompt-safe fragments. The
    # original PDF page number remains unchanged for engineering traceability.
    part_num: int = 1
    part_count: int = 1


DIGEST_PAGES_PER_FILE = 20
# A page-count-only digest is not a reliable request-size bound. With the
# maximum five uploads, the old 20-pages-per-file rule could repeat up to 100
# pages of context on EVERY chunk request. The character caps below keep that
# repeated prefix predictable while still allocating context to every file.
DIGEST_TOTAL_CHAR_BUDGET = 30_000
DIGEST_CHAR_BUDGET_PER_FILE = 30_000
MIN_DIGEST_CHARS_PER_FILE = 3_000

# Detailed review request limits. 45k is the incident-tested text ceiling from
# the production handoff. The page-fragment cap prevents sparse reports from
# combining hundreds of low-text pages into one request.
DEFAULT_CHUNK_CHAR_BUDGET = 45_000
DEFAULT_CHUNK_PAGE_LIMIT = 12
MIN_PAGE_FRAGMENT_CHARS = 2_000

# Scanned/image-only page warning threshold. Detection is deliberately kept
# separate from OCR, which remains outside the current MVP scope.
MIN_MEANINGFUL_CHARS_PER_PAGE = 30


def extract_pages(filename: str, file_bytes: bytes) -> list[Page]:
    """Extract selectable text per page from one PDF's raw bytes."""
    pages: list[Page] = []
    with fitz.open(stream=file_bytes, filetype="pdf") as doc:
        for i, page in enumerate(doc, start=1):
            pages.append(Page(source_file=filename, page_num=i, text=page.get_text("text") or ""))
    return pages


def extract_all(files: list[tuple[str, bytes]]) -> list[Page]:
    """Return the combined, upload-order-preserved page list."""
    fitz.TOOLS.reset_mupdf_warnings()
    all_pages: list[Page] = []
    for filename, file_bytes in files:
        all_pages.extend(extract_pages(filename, file_bytes))
    return all_pages


def get_and_clear_extraction_warnings() -> list[str]:
    """Return recoverable MuPDF warning lines generated by the last extraction."""
    warnings = fitz.TOOLS.mupdf_warnings(reset=True)
    return warnings.splitlines() if warnings else []


def _semantic_cut(text: str, start: int, hard_end: int) -> int:
    """Choose a stable break near ``hard_end`` without dropping characters."""
    if hard_end >= len(text):
        return len(text)

    # Avoid a tiny leading fragment merely to hit an early paragraph boundary.
    search_start = min(
        hard_end,
        start + max(MIN_PAGE_FRAGMENT_CHARS, (hard_end - start) // 2),
    )
    for separator in ("\n\n", "\n", ". ", "; ", ", ", " "):
        idx = text.rfind(separator, search_start, hard_end)
        if idx >= search_start:
            return idx + len(separator)
    return hard_end


def split_page(page: Page, max_text_chars: int) -> list[Page]:
    """Split one extracted PDF page into lossless, traceable fragments.

    This closes the previous loophole where a single page larger than the
    chunk budget was still emitted as one oversized chunk because page
    boundaries were treated as indivisible.
    """
    if max_text_chars <= 0:
        raise ValueError("max_text_chars must be positive")
    if len(page.text) <= max_text_chars:
        return [page]

    fragments: list[str] = []
    pos = 0
    while pos < len(page.text):
        hard_end = min(len(page.text), pos + max_text_chars)
        cut = _semantic_cut(page.text, pos, hard_end)
        if cut <= pos:  # defensive: guarantee forward progress
            cut = hard_end
        fragments.append(page.text[pos:cut])
        pos = cut

    count = len(fragments)
    return [
        Page(
            source_file=page.source_file,
            page_num=page.page_num,
            text=fragment,
            part_num=index,
            part_count=count,
        )
        for index, fragment in enumerate(fragments, start=1)
    ]


def _render_header(page: Page) -> str:
    part_label = (
        f" | part {page.part_num} of {page.part_count}"
        if page.part_count > 1
        else ""
    )
    return f"\n--- [{page.source_file} | page {page.page_num}{part_label}] ---\n"


def _max_render_header_chars(page: Page) -> int:
    """Conservative header size before a page's final fragment count is known."""
    return len(
        f"\n--- [{page.source_file} | page {page.page_num} "
        "| part 999999 of 999999] ---\n"
    )


def _rendered_page_chars(page: Page) -> int:
    return len(_render_header(page)) + len(page.text)


def build_digest(
    pages: list[Page],
    pages_per_file: int = DIGEST_PAGES_PER_FILE,
    total_char_budget: int = DIGEST_TOTAL_CHAR_BUDGET,
    per_file_char_budget: int = DIGEST_CHAR_BUDGET_PER_FILE,
) -> list[Page]:
    """Build a bounded opening-page digest with fair allocation per file.

    The old implementation bounded only page count, so adding more PDFs could
    silently inflate every LLM request. This implementation caps rendered
    characters and prevents the first large report from consuming all context.
    """
    if pages_per_file <= 0 or total_char_budget <= 0 or per_file_char_budget <= 0:
        return []

    by_file: dict[str, list[Page]] = {}
    for page in pages:
        by_file.setdefault(page.source_file, []).append(page)
    if not by_file:
        return []

    file_count = len(by_file)
    fair_share = max(1, total_char_budget // file_count)
    if total_char_budget >= MIN_DIGEST_CHARS_PER_FILE * file_count:
        fair_share = max(MIN_DIGEST_CHARS_PER_FILE, fair_share)
    effective_file_budget = min(per_file_char_budget, fair_share)

    digest: list[Page] = []
    total_used = 0
    for file_pages in by_file.values():
        file_used = 0
        for page in file_pages[:pages_per_file]:
            remaining = min(
                effective_file_budget - file_used,
                total_char_budget - total_used,
            )
            if remaining <= _max_render_header_chars(page):
                break

            rendered_chars = _rendered_page_chars(page)
            if rendered_chars <= remaining:
                selected = page
            else:
                text_budget = remaining - _max_render_header_chars(page)
                if text_budget < MIN_PAGE_FRAGMENT_CHARS:
                    break
                selected = split_page(page, text_budget)[0]

            digest.append(selected)
            used = _rendered_page_chars(selected)
            file_used += used
            total_used += used
            if total_used >= total_char_budget:
                return digest

    return digest


def chunk_pages(
    pages: list[Page],
    char_budget: int = DEFAULT_CHUNK_CHAR_BUDGET,
    max_pages: int = DEFAULT_CHUNK_PAGE_LIMIT,
) -> list[list[Page]]:
    """Create deterministic, prompt-safe detailed review chunks.

    Guarantees:
    * no rendered chunk exceeds ``char_budget``;
    * no chunk exceeds ``max_pages`` page fragments;
    * a chunk never crosses a source-file boundary;
    * a single text-dense page is split losslessly into tagged fragments.
    """
    if char_budget <= 128:
        raise ValueError("char_budget is too small to hold a tagged page")
    if max_pages <= 0:
        raise ValueError("max_pages must be positive")

    fragments: list[Page] = []
    for page in pages:
        max_text_chars = char_budget - _max_render_header_chars(page)
        if max_text_chars <= 0:
            raise ValueError(
                f"char_budget is too small for the page tag generated by {page.source_file!r}"
            )
        fragments.extend(split_page(page, max_text_chars))

    chunks: list[list[Page]] = []
    current: list[Page] = []
    current_chars = 0
    current_source: str | None = None

    for fragment in fragments:
        fragment_chars = _rendered_page_chars(fragment)
        source_changed = bool(current and fragment.source_file != current_source)
        would_exceed_chars = bool(current and current_chars + fragment_chars > char_budget)
        would_exceed_pages = bool(current and len(current) >= max_pages)
        if source_changed or would_exceed_chars or would_exceed_pages:
            chunks.append(current)
            current = []
            current_chars = 0
            current_source = None

        current.append(fragment)
        current_chars += fragment_chars
        current_source = fragment.source_file

    if current:
        chunks.append(current)
    return chunks


def render_pages_as_text(pages: list[Page]) -> str:
    """Flatten pages/fragments into a tagged prompt block."""
    return "".join(_render_header(page) + page.text for page in pages)


def total_page_count(files: list[tuple[str, bytes]]) -> int:
    total = 0
    for _, file_bytes in files:
        with fitz.open(stream=file_bytes, filetype="pdf") as doc:
            total += doc.page_count
    return total


def compute_text_coverage(pages: list[Page]) -> dict:
    """Return a compact summary of pages with little/no selectable text.

    The output schema is intentionally kept compatible with the current
    Streamlit UI and persisted job data.
    """
    total = len(pages)
    low_text = [p for p in pages if len(p.text.strip()) < MIN_MEANINGFUL_CHARS_PER_PAGE]
    return {
        "total_pages": total,
        "low_text_pages": len(low_text),
        "low_text_fraction": round(len(low_text) / total, 3) if total else 0.0,
        "low_text_page_refs": [f"{p.source_file} p{p.page_num}" for p in low_text[:10]],
    }
